### ISSUE TITLE
JAWS add-on speech (prompt) with menus does not include the use of left / right arrow keys, only up / down arrow keys.

### ISSUE THREAD

**Issue by devarshipant** [FreedomScientific/standards-support#411] opened 2020-07-23 12:23 UTC
JAWS speech (prompt) with menus does not include the use of left / right arrow keys, only up / down arrow keys.

> Example:
> 1. Go to https://w3c.github.io/aria-practices/examples/menubar/menubar-navigation.html

> 2. When the first menuitem has focus JAWS does not include instructional prompt to use the left / right arrow keys.

### Expected result

Add reference to "left / right" arrow keys.

**Comment by JAWS-test** [comment] 2020-07-24 06:42
The output should depend on the aria-orientation. 

The question is whether JAWS should produce very detailed output: left-right to navigate through menu items, up and down to navigate through submenu items (or vice versa, depending on the value in aria-orientation).

**Comment by JAWS-test** [comment] 2020-07-24 06:43
Related: https://github.com/FreedomScientific/VFO-standards-support/issues/204

**Comment by devarshipant** [comment] 2020-07-28 13:30
> The output should depend on the aria-orientation.

Correct me but I think aria-orientation only outputs "left-right" and "up-down" depending on the attribute's value, which is first part of the add-on speech. The second bit of add-on speech provides instructions (use arrow keys or use up / down...). See the slider: https://w3c.github.io/aria-practices/examples/slider/slider-2.html. The voice output on the temperature slider is "Temperature **up down** slider. To increase or decrease **use arrow keys**"

> The question is whether JAWS should produce very detailed output: left-right to navigate through menu items, up and down to navigate through submenu items (or vice versa, depending on the value in aria-orientation).

It does not need to be detailed. Perhaps it can give directions on the first menu item. Menus can be tricky because all four keys (up / down and left / right) allow users to navigate in all four different directions, unlike the temperature widget where up and right keys both increase the temperature.

Can menu allow aria-orientation of vertical and horizontal set to true on the same element? Because that might output "[menu name] left-right up-down [menu] use arrow keys to navigate."

**Comment by JAWS-test** [comment] 2020-07-28 14:12
> Correct me but I think aria-orientation only outputs "left-right" and "up-down" depending on the attribute's value

It is a bug in JAWS that aria-orientation is ignored, see https://github.com/FreedomScientific/VFO-standards-support/issues/204

> It does not need to be detailed.

There are different navigation directions in a menu. Within the menubar e.g. right and left, if arranged horizontally. JAWS should always output the direction of the menubar. To navigate in the submenu, use the up and down arrows if menubar is horizontal. In my opinion, JAWS does not necessarily have to output this as a user prompt, since it is derived from the direction of the menubar. It is more important to be able to hear which menu items have a submenu.
It becomes more complicated if a submenu has another submenu. Usually this is arranged vertically, but this does not necessarily have to be the case. For this reason, it may be useful for JAWS to output the direction of navigation for each submenu as soon as it is opened and receives the focus.

**Comment by stevefaulkner** [comment] 2024-01-11 11:00
closing as duplicate of #204

**Closed by stevefaulkner** 2024-01-11 11:00 UTC
