### ISSUE TITLE
Jaws 2019 not reading live child elements in Chrome

### ISSUE THREAD

**Issue by zakeckert** [FreedomScientific/standards-support#222] opened 2019-07-17 17:02 UTC
### Summary
When keyboard focus is on a container element, child elements that are have role="status" or role="alert" won't be read. Non-live elements will be read. This does not happen in Firefox.

Steps to reproduce:
1. Go to https://plnkr.co/edit/klCRt1ZNLZVd7WGxXz7M?p=preview in Chrome
2. Tab through the elements

### Expected result

All text would be read in each of the elements

### Actual result

Text in the green outlined elements is read in its entirety
Text in the red outlined element is not read in its entirety

### Example

https://plnkr.co/edit/klCRt1ZNLZVd7WGxXz7M?p=preview

#### JAWS version and build number

2019.1903.47

 
#### Operating System and version

Windows 10
Edition: Windows 10 Enterprise 
Version: 1903
OS build: 18362.53

#### Browser and version:

Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by JAWS-test** [comment] 2019-07-18 06:39
The problem occurs not only with live regions (such as status, log, alert, dialog, timer, marquee, alertdialog), but also with other ARIA roles, e.g. article, banner, img, term.

The problem occurs only in Edge (Chromium) and Chrome, not in IE and Firefox. 

As long as the bug is not fixed by Freedom Scientific, there are 2 possible solutions:
* for live regions do not use an ARIA role but aria-live
* for live regions or all other roles where the problem occurs, explicitly label the element e.g. via aria-label.

**Comment by lamador** [comment] 2020-06-18 19:03
@zakeckert, please provide the `div ` element with class="broken" in the code sample with an accessible role so that we can accurately test the issue.

**Comment by zakeckert** [comment] 2020-06-18 19:15
I am unable to do that as I have changed jobs and no longer have access to JAWS to properly update the plinkr to accurately reflect the issue.

**Comment by stevefaulkner** [comment] 2023-11-20 18:09
Tested with JAWS 2024 and Chrome 119 on Windows 11, could not reproduce using [test case](https://run.plnkr.co/preview/clp77xmur0006356wnvfhg1cq/)

**Closed by stevefaulkner** 2023-11-20 18:09 UTC
