### ISSUE TITLE
Use of the aria-current attribute is not correctly reflected within the Links List Dialog

### ISSUE THREAD

**Issue by jmegginson** [FreedomScientific/standards-support#773] opened 2023-10-12 16:58 UTC
Reopening a new version of ticket #197 (perhaps closed hastily)

When the aria-current attribute is used on a link, it is correctly announced as being "current" when setting focus to the link in the Virtual Cursor, also when arrowing down the page as expected. 

However, when Insert+F7 is used to display the Links List dialog, the link is described as being "Unavailable", which is misleading because the link is not disabled.

Within the Links List dialog, all current links should also be conveyed as being "Current" so that it matches the description as heard when using the Virtual Cursor.

This issue remains confirmed with latest JAWS in Chrome (118.0.5993.71). This occurs whether aria-current="true" or aria-current="page" is implemented (note that other token values per ARIA 1.2 spec are untested). 

Steps to reproduce:

Open the attached test file within IE11, Chrome, or Firefox.
Arrow down to the Contact link to hear it's current status.
Press Insert+F7 to open the Links List dialog, and arrow to the Contact link.
Confirm that the Contact link is described as being "Unavailable".
Expected result: The Contact link should be described as being "Current" in the Links List dialog.

Actual result: The Contact link in the Links List dialog is conveyed as being "Unavailable".

JAWS version and build number: 2023.2307.37

Operating System and version: Windows 10 64bit

**Comment by stevefaulkner** [comment] 2023-10-28 13:41
duplicate of https://github.com/FreedomScientific/standards-support/issues/97

**Closed by stevefaulkner** 2023-10-28 13:41 UTC
