### ISSUE TITLE
JAWS behavior for read only fields

### ISSUE THREAD

**Issue by aaronbnb** [FreedomScientific/standards-support#798] opened 2024-01-03 21:10 UTC
### Summary

When focused on a read only edit box and forms mode is on with JAWS, using the left and right arrows to navigate text by previous and next character does not result in JAWS reading the characters within this field. In NVDA, in text input mode, (the forms mode on equivalent for JAWS), the same behavior exists.

### Expected result

When pressing the cursor keys, one expects the characters in the field to be read, without exiting forms mode.

### Actual result

It's not possible to read each character without exiting forms mode.

### Example

1. Go to [W3 read only code example](https://www.w3schools.com/tags/tryit.asp?fiename=tryhtml_input_readonly)
2. Set focus to the read only form field with Norway as its value

### Potential actions
1. Allow for JAWS to navigate/read by character in a read only form field when forms mode is on.
OR
2. Automatically enter read mode when focus is on the read only form field. Return to forms mode when focus moves from the read only field.

#### JAWS version and build number
JAWS 2023.2311.34

#### Operating System and version
Windows 10

#### Browser and version:
Chrome 102

**Comment by JAWS-test** [comment] 2024-01-04 06:20
Your link is wrong. Correct is: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_readonly

**Comment by JAWS-test** [comment] 2024-01-04 06:30
The problem also occurs in Edge, but not in Firefox.

I suspect that this is not a fault of JAWS, but of the browser. The cause is that there is no real cursor in read-only input fields in Chrome and Edge. There is only a cursor to change the selection (SHIFT+arrow keys). If I use this cursor, JAWS also correctly outputs the characters in forms mode.

**Comment by JAWS-test** [comment] 2024-01-04 06:33
See https://bugs.chromium.org/p/chromium/issues/detail?id=1265368&q=readonly%20input&can=2

**Comment by aaronbnb** [comment] 2024-01-04 06:45
Thank you. I will add an update to the Chromium bug to validate the impact on user experience and again highlight the issue.

**Comment by stevefaulkner** [comment] 2024-01-06 16:48
closing this for now as it appears to be a browser issue

**Closed by stevefaulkner** 2024-01-06 16:48 UTC
Labels: Chrome bug, triaged
