### ISSUE TITLE
JAWS + Chrome:focus inexplicably moves to role="Heading" element 

### ISSUE THREAD

**Issue by SriHarsha5141** [FreedomScientific/standards-support#172] opened 2019-02-04 13:07 UTC
### Summary

> When using JAWS with  Chrome, interacting with certain elements via down arrow/tab(cursor mode/tab mode) from keyboard and hitting enter will bring focus to a first interactive element that appears in the section.
 
Expected result
Focus should remain on the trigger element.

Actual result
Focus is moving to the first interactive element that appears in the section(dialogue) role="heading" element.

### Example
> login with valid credentials into 'https://msit-test1.visualstudio.com/OneITVSO-Staging/_apps/hub/microsoftitcommontoolsserviceaccount.BotSelfServeAdministration.Microsoft.BotSelfServeAdministration' environment.
**1st instance where we observed the issue:**
> navigating to 'Shared Services Engineering -> Shared Services -> Modern Engineering-> Engineering system', select ;Profile' tab-> 'New child' button.
'Create Area Path' window opens.
Select on 'Create Team' check box and observe the focus order.
Select Save button in the dialogue and observe the focus order.
It is moving to 'Create Area Path' heading.
**2nd instance where we observed the issue:**
Select 'Reports' button from Dashboard page, 'Reports' flyout opens. Observe the focus order.
Focus should move into the 'Reports' flyout.
Focus is moving to the first link present in the top of the Page

#### JAWS version and build number
JAWS Version 2019.1810.64.ILM
 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by lamador** [comment] 2020-06-15 13:49
@SriHarsha5141, we are unable to access the page from the link provided due to the lack of login credentials.  Please provide login information or a code sample of the issue that does not require a login such as CodePen.

**Comment by stevefaulkner** [comment] 2023-11-05 15:16
closing as duplicate of #594

**Closed by stevefaulkner** 2023-11-05 15:16 UTC
Labels: More info needed
